### ISSUE TITLE
How to get Elevenlabs to work?

### ISSUE THREAD

**Issue by frankmeeuwsen** [souzatharsis/podcastfy#199]
Thanks for this excellent package. I use the downloaded package, not the pip install version. I want to try to use custom voices from Elevenlabs but somehow I can't get it to work. 
I have a custom.yaml with tts_model: "elevenlabs" but when I run this I get an error

  File "/Users/Documents/podcastfy/podcastfy/client.py", line 342, in generate_podcast
    tts_model = conversation_config.get("default_tts_model", "openai")
                ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

I am not sure how to proceed from here... an example with custom yaml to use Elevenlabs in another language would be appreciated.

**Comment by souzatharsis** [comment]
Could you please share your custom yaml file?

**Comment by frankmeeuwsen** [comment]
Since I can't upload it, here it is copy-pasted. Thanks for your help!

```yaml
word_count: 400
conversation_style: 
  - "Technical expertise"
  - "Enthusiastic"
podcast_name: "Jobs overview"
roles_person1: "main explainer"
roles_person2: "domain expert"
output_language: "Dutch"
podcast_tagline: "Work on your own careerpath"
engagement_techniques: 
  - "technical know-how"
  - "vivid imagery"
  - "audience prompts"
ending_message: "See our website for more information!"
creativity: 0.7
model: "eleven_multilingual_v2"
default_voices:
  - question: "Frank"
  - answer: "Melanie"
```
